# Generated by Django 4.2.5 on 2023-10-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=100)),
                ('calories', models.IntegerField(null=True)),
                ('fat', models.FloatField(default=0.0, null=True)),
                ('carbs', models.FloatField(default=0.0, null=True)),
                ('protein', models.FloatField(default=0.0, null=True)),
                ('fibres', models.FloatField(default=0.0, null=True)),
            ],
        ),
    ]
