# Generated by Django 4.2.5 on 2023-11-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_consume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consume',
            old_name='food_consumed',
            new_name='foodconsumed',
        ),
        migrations.AlterField(
            model_name='consume',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
